version: 0.0
os: linux
files:
  - source: /requirements.txt
    destination: /home/ec2-user/deploy
  - source: /app.py
    destination: /home/ec2-user/deploy
  - source: /config.py
    destination: /home/ec2-user/deploy
  - source: /gunicorn.py
    destination: /home/ec2-user/deploy
  - source: /init_celery
    destination: /etc/init.d
  - source: /default_celery
    destination: /etc/default
hooks:
  ApplicationStop:
    - location: /stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: /clean.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: /healthcheck.sh
      timeout: 300
      runas: root