version: 0.0
os: linux
files:
  - source: /requirements.txt
    destination: /home/ec2-user/deploy
  - source: /app.py
    destination: /home/ec2-user/deploy
  - source: /config.py
    destination: /home/ec2-user/deploy
  - source: /scripts
    destination: /home/ec2-user/deploy
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root