version: 0.0
os: linux
files:
  - source: /requirements.txt
    destination: /deploy/
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: install.sh
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root