version: 0.0
os: linux
files:
  - source: /requirements.txt
    destination: /home/ubuntu/deploy/flaskapp
  - source: /app_redis/__init__.py
    destination: /home/ubuntu/deploy/flaskapp/app_redis
  - source: /app_redis/app_redis.py
    destination: /home/ubuntu/deploy/flaskapp/app_redis
  - source: /app.py
    destination: /home/ubuntu/deploy/flaskapp
  - source: /config.py
    destination: /home/ubuntu/deploy/flaskapp
  - source: /gunicorn.py
    destination: /home/ubuntu/deploy/flaskapp
  - source: /logs.conf
    destination: /var/awslogs/etc/config
  - source: /flower.service
    destination: /etc/systemd/system
  - source: /gunicorn.service
    destination: /etc/systemd/system
  - source: /gunicorn.socket
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: /stop.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: /clean.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: /install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: /start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: /healthcheck.sh
      timeout: 300
      runas: root