bind = 'localhost:8000'
workers = 6
worker_class = 'sync'
worker_connections = 1000
timeout = 30
daemon = True
user = None
errorlog = '-'
loglevel = 'info'
accesslog = '-'
pid = GFILE
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
